spring:
  .datasource:
    .url: jdbc:mysql://rc1b-0jxb91ubshr2u7p1.mdb.yandexcloud.net:3306/search_engine?allowPublicKeyRetrieval=true&useSSL=true
    .username: rootUser
    .password: subjik-wembuf-dazRy3
#    url: jdbc:mysql://localhost:3306/search_engine?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#    username: root
#    password: 9511040801
    .testWhileIdle: true
    .validationQuery: SELECT 1
    .hikari:
      connection-timeout: 600000
      maximum-pool-size: 500
  .jpa:
    .hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      show_sql: true
      current_session_context_class: thread
      ddl-auto: update
sites:
  description: write sites here for indexing
  list:
    - url: https://nikoartgallery.com
      name: Галерея Никогосяна
    - url: https://dombulgakova.ru
      name: Музей-театр
    - url: http://radiomv.ru
      name: Радио Милицейская волна
    - url: http://www.playback.ru
      name: Интернет-магазин
connect:
  userAgent: RevivalSearchBot
  refferer: http://www.google.com
  pathToWeb: /admin