spring:
  datasource:
#    url: jdbc:mysql://rc1c-fei86sviy3yabf9t.mdb.yandexcloud.net:3306/search_engine?allowPublicKeyRetrieval=true&useSSL=true&serverTimezone=UTC
#    username: rootUser
#    password: subjik-wembuf-dazRy3
    url: jdbc:mysql://localhost:3306/search_engine?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 9511040801
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      show_sql: true
      current_session_context_class: thread
      ddl-auto: update
sites:
  description: write sites here for indexing
  list:
    - url: https://nikoartgallery.com
      name: Галерея Никогосяна
    - url: https://dombulgakova.ru
      name: Музей-театр
    - url: http://radiomv.ru
      name: Радио Милицейская волна
    - url: https://ipfran.ru
      name: Институт прикладной физики
connect:
  userAgent: RevivalSearchBot
  refferer: http://www.google.com
  pathToWeb: /admin